spring:
  application:
    name: 3runner-front

  data:
    redis:
      host: 133.186.241.167
      port: 6379
      database: 11
      password: "*N2vya7H@muDTwdNMR!"

  security:
    oauth2:
      client:
        registration:
          payco:
            client-id: 3RDUR8qJyORVrsI2PdkInS1
            client-secret: yoA1FPvf5ievEnC7LkzJDp1x
            redirect-uri: http://3runner.shop/oauth2/callback/payco
            authorization-grant-type: authorization_code
            scope: idNo, email, mobile, name
        provider:
          payco:
            authorization-uri: https://id.payco.com/oauth2.0/authorize
            token-uri: https://id.payco.com/oauth2.0/token
            user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

  profiles:
    active: prod
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jwt:
    secret: aaaasqwlkljlfasdfqwerafcxvzpojijoijopjewndllllllsserrrrrrwqexc

  rabbitmq:
    host: 133.186.241.167
    port: 5672
    username: admin
    password: nhnacademy123!

  cloud:
    openfeign:
      client:
        config:
          default:
            error-decoder: com.nhnacademy.front.config.CustomErrorDecoder
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 3
      max-total: 5
      max-idle: 5
      min-idle: 3
      test-on-borrow: true
      validation-query: SELECT 1


springdoc:
  swagger-ui:
    url: /docs/openapi-3.0.json
    path: /docs/swagger