package com.nhnacademy.front.entity.purchase.enums;

public enum PurchaseStatus {
	PROCESSING, COMPLETED, DELIVERY_START, DELIVERY_PROGRESS,
	DELIVERY_COMPLETED, REFUNDED_REQUEST, REFUNDED_COMPLETED, CONFIRMATION
}
